### ISSUE TITLE
French airspace outdated

### ISSUE THREAD

**Issue by mlep** [XCSoar/xcsoar-data-repository#151]
I have just updated the French airspace for XCSoar, using its download feature.
The header of the file shows this version is one year old:
````
*                        SOURCE: AIP FRANCE 2019/05/23                         *
*                               Version 2019-05                                *
*                           Fichier crée 23 mai 2019  
````

The French soaring federation (FFVP) currently hosts a much recent version:
````
*                        SOURCE: AIP FRANCE 2020/04/23                      *
````

Looking at the file https://github.com/XCSoar/xcsoar-data-repository/blob/master/data/airspace.json , I notice the French airspace comes from the URL: http://soaring.gahsys.com/Airspace/FR/190523__AIRSPACE_FRANCE_2019-05.txt

How to make the most recent FFVP airspace file available to all XCSoar's users?

**Comment by rawtaz** [comment]
What is the URL for the most recent version? Once you have that URL, it's a simple matter of opening a PR, which you can do the following way:

- Go to https://github.com/XCSoar/xcsoar-data-repository/blob/master/data/airspace.json .
- Click the Edit button (the icon with a pencil).
- Find and change the "http://soaring.gahsys.com/Airspace/FR/190523__AIRSPACE_FRANCE_2019-05.txt" to the new URL (keeping it in quotes), and the corresponding date three lines below the URL line (this date should be when the airspace data/file was updated, which you can usually find inside or alongside the file at the source).
- At the bottom of the editing page, under the "Commit changes" heading, choose "Create a new branch for this commit and start a pull request", write something like "Update France airspace" in the one-line description field right under the "Commit changes" heading, then click "Commit changes".
- On the next page, follow the instructions to open a pull request.
- In the multi-line description textarea of the pull request form, make sure to include "Closes #151" which will then reference this issue.

After this you're a contributor and know how to contribute code/stuff on GitHub!

**Comment by mlep** [comment]
Thanks for the detailed explanation.
So, the main issue is about the URL...
The current version is on a google drive: https://drive.google.com/file/d/1RbG6aIQThAYs5EcUOJF1bPG7QfQXbrd1/view

- I am not sure if this URL will be the same for the next version.
- You need to click on "download" to download the file...

**Comment by rawtaz** [comment]
Thanks for checking. Not too happy about Google Drive being involved, but it is what it is unless someone knows a better place to get the file.

The direct download URL for the file is: https://drive.google.com/uc?export=download&id=1RbG6aIQThAYs5EcUOJF1bPG7QfQXbrd1

I got that URL by using https://sites.google.com/site/gdocs2direct/ but one can just edit the URL manually otherwise.

Can you try to file a PR with that URL (don't forget to update the date as well)?

**Comment by mlep** [comment]
OK, I will do this.
Nice trick to get the direct download URL!

**Comment by lordfolken** [comment]
Argh.. google drive for something as vital and important as this. 
Can you motivate the FFVP to provide an official download link on a serious server? They get enough money from me every year.

My experience with dropbox and google drive links is that they expire and die. 

An option is to host it with http://soaringweb.org. Send the updated file to john leibacher. 

Then we can link to it with a stable service.

**Comment by rawtaz** [comment]
Why not send it to the place that hosts the currently used file instead, http://soaring.gahsys.com/Airspace/HomePage.html (john.leibacher@gmail.com)?

**Comment by mlep** [comment]
- OK for sending the file to the suitable person. Just me know who, please. :wink:
- OK for contacting the FFVP.

**Comment by mlep** [comment]
- OpenAir file sent to John Leibacher.
- Request for a proper URL sent to FFVP.

I will create a PR to update the file https://github.com/XCSoar/xcsoar-data-repository/blob/master/data/airspace.json when needed.

**Comment by rawtaz** [comment]
Yeah, that's great, let's put this issue on hold until we get a better URL to use :) Nice work!

**Comment by mlep** [comment]
Prompt reply from the FFVP airspace commission:
- not possible to keep the same name for the OpenAir file because the version of the file must be visible from its name (FFVP rule).
- the FFVP uses GoogleDrive to unify and simplify the access to important information

Hopeless...

**Comment by mlep** [comment]
And prompt reply from John L.: he will upload the file ASAP.
I will take care of the file airspace.json afterward.

**Comment by rawtaz** [comment]
Nice work @mlep, well done. Was this your first PR?

**Comment by mlep** [comment]
@rawtaz. Thanks. No, it was not (I do not contribute code, but documentation, translation, etc.)

**Comment by rawtaz** [comment]
Ah, well then, I didn't mean to suggest you were a beginner, I just assumed you hadn't made PRs before. Sorry about that, and thanks again!

**Comment by mlep** [comment]
@rawtaz  No offense! Cheers.
