### ISSUE TITLE
soaringweb.org urls not properly checked in travis

### ISSUE THREAD

**Issue by lordfolken** [XCSoar/xcsoar-data-repository#32]
Hi, 

soaringweb.org doesn't supply proper 404 return codes...

It supplies the following webpage: 

<HTML>
<head>
<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
<style type="text/css">
a:link {text-decoration: underline}
a:hover {text-decoration: underline; color: red}
</style>
<base href="http://soaringweb.org">
<meta name="Description" content="Website for Dr. G&uuml;nther Eichhorn (Dr. Guenther Eichhorn), for traveling and aerobatics flying: Data Service Message">
<meta name="Keywords" content="Dr. Guenther Eichhorn, Dr. G&uuml;nther Eichhorn, Dr. Gunther Eichhorn, Traveling, Aerobatics Flying, Pictures, Photographs">
<TITLE>Data Service Message</TITLE>
<script language="JavaScript" type="text/javascript">

</script>
</head>
<body bgcolor="#ffffff" text="#000000" link="#0000ff" alink="#ff0000" vlink="#4000a0">
<a name="top"><br></a>
<h3>Data Service Message</h3>
<hr>
<h3>Can't read file</h3>
</body></html>

This is why several changes haven't been caught. France Airspace is not good, neither is Canada, and the rest i haven't checked yet.

**Comment by Turbo87** [comment]
I guess it would be best to download the files and run them through an airspace file parser

**Comment by lordfolken** [comment]
I wrote an email to John Leibacher, to ask wheter its possible to change the soaringweb.org's website software to throw 404s.

**Comment by lordfolken** [comment]
No reply from John, as of yet.

**Comment by lordfolken** [comment]
This was fixed some time ago. soaringweb now does proper 404s. :)
