### ISSUE TITLE
File availability script

### ISSUE THREAD

**Issue by Turbo87** [XCSoar/xcsoar-data-repository#6]
This repository should have a small script that checks if the referenced files are still available.

**Comment by fb** [comment]
What about providing all data files on download.xcsoar.org and using https://github.com/buildinspace/peru? It's able to tracks file's checksums.

**Comment by TB-Mirror** [comment]
Because in some cases we might not be allowed to redistribute the files...

**Comment by fb** [comment]
You are right. This could be problematic for some of the files.

**Comment by Turbo87** [comment]
fixed by #9
