### ISSUE TITLE
Type missing for romania airspace

### ISSUE THREAD

**Issue by pyrog** [XCSoar/xcsoar-data-repository#64]
[data/airspace.json](https://github.com/XCSoar/xcsoar-data-repository/blob/master/data/airspace.json)

```json
    { "name": "Romania_Airspace.txt", 
      "uri": "http://soaringweb.org/Airspace/RO/romanian_airspace_2016.02.22.txt",
      "area": "ro", 
      "update": "2016-10-07"
    }, 

```
Probably **airspace** file type 😉

**Comment by Turbo87** [comment]
indeed, it seems that https://github.com/XCSoar/xcsoar-data-repository/commit/3a1365332f4bb73a72726058d1788bd08c822788 was not formatted properly.

/cc @lordfolken
