### ISSUE TITLE
Insert Netherlands airspace into this repository

### ISSUE THREAD

**Issue by roeles** [XCSoar/xcsoar-data-repository#67]
Maurits Dortu from GliderPilotShop, the author of the Netherlands airspace file, gave permission by email to Roel Baardman to host a copy of the airspace file.
This file should only be updated when the original author updates the file.

Besides adding the original file to this repository, the link in the JSON-file should also be updated.

**Comment by roeles** [comment]
Asked the author for the latest version of the file. Awaiting response.

**Comment by Turbo87** [comment]
@roeles cool, thanks for taking care of this.

we can likely just use the "raw" link of GitHub to download the file to devices (e.g. https://github.com/XCSoar/xcsoar-data-repository/blob/8b08befc51aa72162e36c543d0a39871e8196610/data/flarmnet.json)

**Comment by roeles** [comment]
Yeah, that's what I plan to do.

**Comment by roeles** [comment]
The airspace is now available:
https://www.gliderpilotshop.com/databases

 I have permission to copy it into github. 
I wonder:
-  what is the proposed location for the new airspace file? 
- Do we have preferences for file naming? The current filename is EHv17_3.txt, but this includes the version. I could reduce it to EH.txt, but perhaps we want to use some other filename extension or naming?

**Comment by Turbo87** [comment]
> what is the proposed location for the new airspace file?

I'd say put it in `data/airspace/nl.txt`.

> Do we have preferences for file naming? The current filename is EHv17_3.txt, but this includes the version. I could reduce it to EH.txt, but perhaps we want to use some other filename extension or naming?

Since we would/should include the SHA1 in the download link it would already be versioned so I'd say we should probably just use the official country code (e.g. `nl` in this case)

**Comment by Turbo87** [comment]
resolved by https://github.com/XCSoar/xcsoar-data-repository/pull/68
