### ISSUE TITLE
Kobo can't do SSL URLS

### ISSUE THREAD

**Issue by lordfolken** [XCSoar/xcsoar-data-repository#73]
I noted that the kobo wget binary is built without ssl. This is problematic as it cannot download repo content via https. Currently all the urls have been changed to http until https://bugs.xcsoar.org/ticket/3842 is resolved

**Comment by Turbo87** [comment]
ugh... seriously?!

**Comment by hor63** [comment]
Not only Kobo. Also older Androids (checked with Android 4.1, and 3.1) have outdated certificates which cause failing HTTPS connections.

**Comment by lordfolken** [comment]
Should we ship a downloading component with xcsoar, which contains the certificate?

**Comment by lordfolken** [comment]
There seems to be a solution now with the wolfssl library which would allow us to supply a decent ssl library with the same license as the main program.

**Comment by lordfolken** [comment]
This is fixed in master with openssl now being included: https://github.com/XCSoar/XCSoar/commit/4eb6abde5450a58a6b1ba70efe312c30f20646bf
