### ISSUE TITLE
Airfield frequencies in `Germany.cup` are outdated

### ISSUE THREAD

**Issue by Turbo87** [XCSoar/xcsoar-data-repository#86]
Some of the airfield radio frequencies in Germany changed this year and due to that our `Germany.cup` file is now outdated.

**Comment by Turbo87** [comment]
I just looked at https://openflightmaps.org/live/ed-germany/ and it does not seem to contain the frequencies for most of the smaller airfields 🤔

**Comment by RBE-Avionik** [comment]
I did something regarding this, see : https://bugs.xcsoar.org/ticket/3891

**Comment by Turbo87** [comment]
unfortunately that link requires a login to access the file. I've extracted it and uploaded it here for backup: [Germany.cup](https://github.com/XCSoar/xcsoar-data-repository/files/1908574/Germany.cup.txt)
